version: "3"

services:

  web:
    build: .
    restart: always
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - .:/code
    ports:
      - "80:80"
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'

  db:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
  cache:
    image: redis
